package com.domain.BaseModels

import com.google.gson.annotations.SerializedName

data class BodyCandidateList(

    @SerializedName("counter"             ) var counter             : Int?    = 0,
    @SerializedName("primaryCounter"      ) var primaryCounter      : Int?    = 0,
    @SerializedName("skillsearch1"        ) var skillsearch1        : String? = "",
    @SerializedName("skillsearch2"        ) var skillsearch2        : String? = "",
    @SerializedName("skillsearch3"        ) var skillsearch3        : String? = "",
    @SerializedName("skillsearch4"        ) var skillsearch4        : String? = "",
    @SerializedName("skillsearch5"        ) var skillsearch5        : String? = "",
    @SerializedName("primaryskillsearch1" ) var primaryskillsearch1 : String? = "",
    @SerializedName("primaryskillsearch2" ) var primaryskillsearch2 : String? = "",
    @SerializedName("primaryskillsearch3" ) var primaryskillsearch3 : String? = "",
    @SerializedName("primaryskillsearch4" ) var primaryskillsearch4 : String? = "",
    @SerializedName("primaryskillsearch5" ) var primaryskillsearch5 : String? = "",
    @SerializedName("city"                ) var city                : String? = "",
    @SerializedName("state"               ) var state               : String? = "",
    @SerializedName("country"             ) var country             : String? = "",
    @SerializedName("work_auth"           ) var workAuth            : String? = "",
    @SerializedName("fromdate"            ) var fromdate            : String? = "",
    @SerializedName("todate"              ) var todate              : String? = "",
    @SerializedName("videoStatus"         ) var videoStatus         : String? = "All",
    @SerializedName("techStatus"          ) var techStatus          : String? = "All",
    @SerializedName("search"              ) var search              : String? = "",
    @SerializedName("recruitervalue"      ) var recruitervalue      : String? = "",
    @SerializedName("RecruiterSearch"     ) var RecruiterSearch     : String? = ""

)

data class ResponseCandidateList (

    @SerializedName("savedProfileDetail"      ) var savedProfileDetail      : ArrayList<SavedProfileDetail> = arrayListOf(),
    @SerializedName("totalCount"              ) var totalCount              : Int?                          = null,
    @SerializedName("MSAppDelegatePermission" ) var MSAppDelegatePermission : String?                       = null,
    @SerializedName("MSMeetingPlatform"       ) var MSMeetingPlatform       : String?                       = null

)


data class SavedProfileDetail (

    @SerializedName("id"                                 ) var id                                 : Int?    = null,
    @SerializedName("MadeAssagement"                     ) var MadeAssagement                     : String? = null,
    @SerializedName("PkSaveProfileId"                    ) var PkSaveProfileId                    : Int?    = null,
    @SerializedName("Name"                               ) var Name                               : String? = null,
    @SerializedName("Email"                              ) var Email                              : String? = null,
    @SerializedName("Secondary_Email"                    ) var SecondaryEmail                     : String? = null,
    @SerializedName("Phone"                              ) var Phone                              : String? = null,
    @SerializedName("Secondary_contact"                  ) var SecondaryContact                   : String? = null,
    @SerializedName("Skype"                              ) var Skype                              : String? = null,
    @SerializedName("currentLocation"                    ) var currentLocation                    : String? = null,
    @SerializedName("Availability"                       ) var Availability                       : String? = null,
    @SerializedName("Age"                                ) var Age                                : Int?    = null,
    @SerializedName("Relocation"                         ) var Relocation                         : String? = null,
    @SerializedName("Profilestatus"                      ) var Profilestatus                      : String? = null,
    @SerializedName("Resume"                             ) var Resume                             : String? = null,
    @SerializedName("Dateofbirth"                        ) var Dateofbirth                        : String? = null,
    @SerializedName("ssn_issue_Date"                     ) var ssnIssueDate                       : String? = null,
    @SerializedName("linkedin"                           ) var linkedin                           : String? = null,
    @SerializedName("Skills"                             ) var Skills                             : String? = null,
    @SerializedName("primarySkills"                      ) var primarySkills                      : String? = null,
    @SerializedName("Experience"                         ) var Experience                         : String? = null,
    @SerializedName("citizenship"                        ) var citizenship                        : String? = null,
    @SerializedName("securityclerance"                   ) var securityclerance                   : Int?    = null,
    @SerializedName("work_auth"                          ) var workAuth                           : String? = null,
    @SerializedName("Travel"                             ) var Travel                             : String? = null,
    @SerializedName("work_weekend"                       ) var workWeekend                        : Int?    = null,
    @SerializedName("UserId"                             ) var UserId                             : String? = null,
    @SerializedName("Score"                              ) var Score                              : Int?    = null,
    @SerializedName("VoiceVerified"                      ) var VoiceVerified                      : String? = null,
    @SerializedName("AgeVerificationCode"                ) var AgeVerificationCode                : String? = null,
    @SerializedName("AgeVerificationCodeDescription"     ) var AgeVerificationCodeDescription     : String? = null,
    @SerializedName("LicenseFrontImagePath"              ) var LicenseFrontImagePath              : String? = null,
    @SerializedName("LicenseBackImagePath"               ) var LicenseBackImagePath               : String? = null,
    @SerializedName("LicenseVerificationCode"            ) var LicenseVerificationCode            : String? = null,
    @SerializedName("LicenseVerificationCodeDescription" ) var LicenseVerificationCodeDescription : String? = null,
    @SerializedName("LastInterviewDetails"               ) var LastInterviewDetails               : String? = null,
    @SerializedName("LastInterviewDetailss"              ) var LastInterviewDetailss              : String? = null,
    @SerializedName("LastScheduledAssessment"            ) var LastScheduledAssessment            : String? = null,
    @SerializedName("LastScheduledAssessments"           ) var LastScheduledAssessments           : String? = null,
    @SerializedName("LastAvailableAudioCallId"           ) var LastAvailableAudioCallId           : String? = null,
    @SerializedName("lastInterviewTimeZone"              ) var lastInterviewTimeZone              : String? = null,
    @SerializedName("lastScheduledAssessmentTimeZone"    ) var lastScheduledAssessmentTimeZone    : String? = null,
    @SerializedName("LastVideoAudioCallIds"              ) var LastVideoAudioCallIds              : String? = null,
    @SerializedName("RecordNewSampleEnabled"             ) var RecordNewSampleEnabled             : Int?    = null,
    @SerializedName("TotalCount"                         ) var TotalCount                         : Int?    = null,
    @SerializedName("ProfilerUrl"                        ) var ProfilerUrl                        : String? = null,
    @SerializedName("Average"                            ) var Average                            : Int?    = null,
    @SerializedName("ReferenceCheckStatus"               ) var ReferenceCheckStatus               : String? = null,
    @SerializedName("IsResumeExists"                     ) var IsResumeExists                     : String? = null,
    @SerializedName("skillsearch1"                       ) var skillsearch1                       : String? = null,
    @SerializedName("skillsearch2"                       ) var skillsearch2                       : String? = null,
    @SerializedName("skillsearch3"                       ) var skillsearch3                       : String? = null,
    @SerializedName("skillsearch4"                       ) var skillsearch4                       : String? = null,
    @SerializedName("skillsearch5"                       ) var skillsearch5                       : String? = null,
    @SerializedName("counter"                            ) var counter                            : Int?    = null,
    @SerializedName("primaryskillsearch1"                ) var primaryskillsearch1                : String? = null,
    @SerializedName("primaryskillsearch2"                ) var primaryskillsearch2                : String? = null,
    @SerializedName("primaryskillsearch3"                ) var primaryskillsearch3                : String? = null,
    @SerializedName("primaryskillsearch4"                ) var primaryskillsearch4                : String? = null,
    @SerializedName("primaryskillsearch5"                ) var primaryskillsearch5                : String? = null,
    @SerializedName("primaryCounter"                     ) var primaryCounter                     : Int?    = null,
    @SerializedName("city"                               ) var city                               : String? = null,
    @SerializedName("state"                              ) var state                              : String? = null,
    @SerializedName("fromdate"                           ) var fromdate                           : String? = null,
    @SerializedName("todate"                             ) var todate                             : String? = null,
    @SerializedName("updated"                            ) var updated                            : String? = null,
    @SerializedName("subscriberid"                       ) var subscriberid                       : String? = null,
    @SerializedName("videoStatus"                        ) var videoStatus                        : String? = null,
    @SerializedName("techStatus"                         ) var techStatus                         : String? = null,
    @SerializedName("search"                             ) var search                             : String? = null,
    @SerializedName("Recruitervalue"                     ) var Recruitervalue                     : String? = null,
    @SerializedName("Countrycode"                        ) var Countrycode                        : Int?    = null,
    @SerializedName("country"                            ) var country                            : String? = null,
    @SerializedName("RecruiterSearch"                    ) var RecruiterSearch                    : String? = null,
    @SerializedName("CreatedDate"                        ) var CreatedDate                        : String? = null,
    @SerializedName("UpdatedBy"                          ) var UpdatedBy                          : String? = null,
    @SerializedName("SourceDetails"                      ) var SourceDetails                      : String? = null,
    @SerializedName("TPSID"                              ) var TPSID                              : Int?    = null,
    @SerializedName("NameInitials"                       ) var NameInitials                       : String? = null

)


